### PR TITLE
Add Erlang analyzer

### PR DESCRIPTION
**Pull request by trondn**
This patch is a modification of the patches created by
Haitao Li <lihaitao@gmail.com> back in 2011 and made available
at https://bitbucket.org/liht/opengrok/branch/erlang-analyzer

The OCA is accepted

### CODE REVIEW

**Comment by lht** [comment]
I accept and am OK with OCA for this patch.

**Comment by tarzanek** [comment]
great, I guess we only miss some junits, but that can be done later ... accepting, since Travis passed
@trondn  @lht will one of you be available to write a junit for the analyzer so it's covered?

**Comment by tarzanek** [comment]
hmm, I accepted an we miss copyrights, ok will add them later
...

**Comment by tarzanek** [comment]
hmm, one more thing we forgot - add this to SearchHelper.java
into filedescriptions ... will fix with copyright ...

**Comment by tarzanek** [comment]
see #912

**Comment by tarzanek** [comment]
alt. I should rewrite in how we generate the filedescriptions - they should come from analyzers, this data should be isolated inside analyzer and not taken from helper class (but helper class should build it from the known analyzer list)

**Pull request merged**
