### PR TITLE
using multiple default projects

### PR DESCRIPTION
**Pull request by tulinkry**
Implements enhancement proposed in #1357 and also back in old days in #28

### CODE REVIEW

**Comment by vladak** [comment]
pls resolve the conflicts. I will take a look afterwards.

**Comment by tulinkry** [comment]
Resolved

**Comment by vladak** [comment]
Couple of notes:
  - I wonder if this should be reflected in the `OpenGrok` shell script ?
  - pls also change the usage CommandLineOptions.java
  - some test+documentation for the `__all__` special value ?

**Comment by tulinkry** [comment]
> pls also change the usage CommandLineOptions.java

changed

> some test+documentation for the __all__ special value ?

added a test case + documented the `__all__` in the usage

**Comment by tulinkry** [comment]
> I wonder if this should be reflected in the OpenGrok shell script ?

I don't see that the wrapper support default project. This could be part of another enhancements in different PR.

**Comment by vladak** [comment]
okay then. pls file a new enhancement for the `OpenGrok` shell script.

**Pull request merged**
