### PR TITLE
Return absolute path for scripts if contextPath is empty

### PR DESCRIPTION
**Pull request by caminada**
Signed-off-by: Daniel Caminada <daniel.caminada@ergon.ch>

### CODE REVIEW

**Comment by caminada** [comment]
We are running grok as root application on tomcat, thus no "/source" is present in the url. This ends up in javascript files not been able to be loaded because the rendered paths are relative:

```
</div>
	<script type="text/javascript" src="js/jquery-3.2.0.min.js" data-priority="10"></script>
	<script type="text/javascript" src="js/jquery-ui-1.12.0-custom.min.js" data-priority="11"></script>
	<script type="text/javascript" src="js/jquery-tablesorter-2.26.6.min.js" data-priority="12"></script>
	<script type="text/javascript" src="js/tablesorter-parsers-0.0.1.js" data-priority="13"></script>
	<script type="text/javascript" src="js/searchable-option-list-2.0.3.min.js" data-priority="14"></script>
	<script type="text/javascript" src="js/utils-0.0.13.js" data-priority="15"></script>
</body>
```

**Comment by vladak** [comment]
Looks like `ScriptsTest.testLookup` test failed.

**Comment by vladak** [comment]
Looks sane to me, although I'd like to hear from @tulinkry as well.

In the meantime, do you have OCA ?

**Comment by caminada** [comment]
yes, oca was sent here: https://github.com/OpenGrok/OpenGrok/pull/1141#issuecomment-235930571

**Comment by tarzanek** [comment]
merging, thank you

**Pull request merged**
