### PR TITLE
Allow scrolling on long source files with no JS enabled

### PR DESCRIPTION
**Pull request by djgilcrease**
This uses CSS to size and position the elements on the page so you can still scroll when there is no JS enabled

### CODE REVIEW

**Comment by tarzanek** [comment]
Looks good to me, there are 2 more styles can you fix those too please?
I'd also need you to accept OCA - oracle contributor agreement before accepting the patch.
Either just say you accept for this patch here or get oca from Oracle pages and mail them a scanned copy to get registered for any patch to oracle, your choice ... 
Tia
L

**Comment by tarzanek** [comment]
link to OCA: http://www.oracle.com/technetwork/community/oca-486395.html

**Comment by tarzanek** [comment]
and the styles are in:
https://github.com/OpenGrok/OpenGrok/tree/master/web/offwhite
and
https://github.com/OpenGrok/OpenGrok/tree/master/web/polished

**Comment by djgilcrease** [comment]
I updated the other themes as well, and submitted the OCA

**Comment by tarzanek** [comment]
great, I just recieved your OCA, you should be on Oracle page listed in few hours (or a day, not sure how fast the pages reflect the change)
I will try to integrate this today too

**Comment by tarzanek** [comment]
perhaps one last Q - what combos did you test? (we don't have any automated test suites for BUI, so we rely heavily on users)
I usually do win7 + latest FF, Opera, Chrome and IE
then debian stable + FF, Chrome
I can also try Win 10 + FF, Opera, Chrome + IE and Edge of course

with your above changes I'd hope that lynx/links/elinks will work too! :-D

**Comment by djgilcrease** [comment]
Win7 - Chrome latest (47), FF Latest (41), IE 11
Ubuntu - Chrome latest, FF Latest

I only really tested the default theme since that is the one our deployment uses

**Comment by tarzanek** [comment]
thank you sir, merging!
if you can retest the other themes it'd be wonderful

**Comment by tarzanek** [comment]
@djgilcrease hmm ... I just tested @trondn site on windows 10 + latest FF and it's broken
http://src.couchbase.org/source/search?q=test&defs=&refs=&path=&hist=&type=&project=3.1.0

**Comment by tarzanek** [comment]
@djgilcrease I reverted your code until this will be fixed
I tried Opera, it's also broken
@trondn tried something else (I suppose some mac, solaris or linux combo) and it was also broken, all elements were behind header ... 
I think we will need some better redesign of my original fixed header ... it's 2015 and this code is sooo 2007 :(

**Comment by trondn** [comment]
@tarzanek +1 for refactoring ;)

**Comment by tarzanek** [comment]
@trondn haha ... now I just need to clone myself ;)
@djgilcrease I have no probs re accepting this patch once you revise it and retest, I am curious if css will be able to handle this design I whipped up long time ago.
But truth is, it really needs fixing ... :(

**Comment by djgilcrease** [comment]
I am looking into it to do additional testing, but I got pulled off this to other bugs at work so it may be a few weeks before I get full testing done

**Comment by tarzanek** [comment]
@djgilcrease no prob, take your time, so we don't have to play the backout game again ;)

**Pull request merged**
