### PR TITLE
Don't use user-defined Golang mapping command options with Universal ctags

### PR DESCRIPTION
**Pull request by patricklundquist**
Addresses issue #1002

### CODE REVIEW

**Comment by tarzanek** [comment]
looks great, same Q regarding OCA - http://www.oracle.com/technetwork/community/oca-486395.html
if you accept state it, or get the registration in Oracle to avoid this silly questioning :(

**Comment by tarzanek** [comment]
(I have to get the "accept  OCA" per patch, I cannot do it once for all, that's why the registration is there ... )

**Comment by patricklundquist** [comment]
Thanks Lubos, I'll look into registering. 

I'm OK with OCA for this patch.

**Comment by tarzanek** [comment]
thank you, in the gate now! :)

**Pull request merged**
