### PR TITLE
Add help documentation of Intelligence Window and Symbol Highlighting.

### PR DESCRIPTION
**Pull request by harryxp**

### CODE REVIEW

**Comment by tulinkry** [comment]
I'm reworking the window to use jquery and to a little different design so the screens should be updated then

**Comment by tarzanek** [comment]
@tulinkry should I wait for you then?
or will you take new screenshots and update them if I accept this PR first?

**Comment by tarzanek** [comment]
and btw. pictures for other styles are missing (offwhite and polished)

**Comment by tulinkry** [comment]
Yes I will update all of them with the new view

**Comment by tarzanek** [comment]
ok, thanks Harry, merging, Krystof - you will have to add screenshots to all styles

**Pull request merged**
