### PR TITLE
set HTTP error codes for error conditions

### LINKED ISSUE #17: "Index database(s) not found." should not be `200 OK`
When the index database is temporarily gone, OpenGrok returns `"Index database(s) not found."` (https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/web/SearchHelper.java) with a `200 OK` HTTP status code.

This breaks down HTTP accelerators (and probably various web-crawlers, too), which cache error pages momentarily (seconds), but non-error pages for an extended period of time (minutes or hours), where such OpenGrok error pages will be cached extensively, instead of being expired promptly.  Plus web-crawlers might update its index, instead of ignoring the result, and trying back later.

With `"Index database(s) not found."`, a non-200 http status code should be returned instead, probably `503 Service Unavailable`.

### PR DESCRIPTION
**Pull request by vladak**
fixes #17

### CODE REVIEW

**Comment by tulinkry** [comment]
This is ok. However I'm not sure if this doesn't go against the problem in #517.

**Comment by vladak** [comment]
I think the multisearch issue is effectively about hiding the failure so it should not clash.

**Comment by vladak** [comment]
Actually yes, there is a conflict. However the fix for #517 would have to radically change this area anyway (need to return `MultiReader` and at the same time error condition about project(s) with invalid indexes) so making the current code behaving correctly is more important I think.

**Comment by tulinkry** [comment]
Ok

**Pull request merged**
