### PR TITLE
Option parser 1503 ... cleanup

### PR DESCRIPTION
**Pull request by shaehn**
This request is to finish off the OptionParser.java and Indexer.java integration. It fixes Indexer.java compile error and removes CommandLineOptions.java and CommandLineOptionsTest.java for #1503

### CODE REVIEW

**Comment by tarzanek** [comment]
don't change the chmod of executable files to 644 please ... revert this

**Comment by tarzanek** [comment]
was CommandLineOptionsTest moved to new way how we handle options?
I don't want to loose tests that cover us ...

**Comment by shaehn** [comment]
CommandLineOptionsTest was removed because there is no longer a CommandLineOptions class.

**Comment by shaehn** [comment]
What file(s) got permissions changed to 644?  All I did was merge with the master branch.

**Comment by tarzanek** [comment]
and the tests that were in that class were brought over to new class ?

**Comment by shaehn** [comment]
No, new tests were written (see OptionParserTest.java)

**Comment by tarzanek** [comment]
ah, ok, so now just to figure out why the mode change happened

**Comment by shaehn** [comment]
ok, something weird is going on here. I wrote a bunch of tests for OpenParser and I am not seeing the file.

**Comment by shaehn** [comment]
Nevermind, I found the file. Lubos, you're making me paranoid.

**Comment by vladak** [comment]
All right, given this PR contains already integrated changesets and also unwanted permission changes, I am going to merge this by hand.

**Comment by tarzanek** [comment]
@shaehn permissions are tricky with Windows ... beware of this, git saves permissions, so anytime you change an executable unix file on windows you will mess up the permissions

**Pull request closed without merging**
