### PR TITLE
Add MandocAnalyzer and OPENGROK_MANDOC setting

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to allow designating a mandoc(1) binary to be used for formatting mdoc(5) and man(5) documents — or if no binary is specified, then to detect and use the PlainTextAnalyzer for mdoc(5) documents, since TroffXref does not properly format these files.

As part of this patch, I added a DocumentMatcher class to be used by both TroffAnalyzerFactory and the new MandocAnalyzerFactory. The formerly-specified "magics" for TroffAnalyzerFactory were too imprecise to be used for distinguishing mdoc(5) and man(5) — but because they were "MAGICS" they were treated as precisely matching.

To reiterate: if a mandoc(1) binary is designated, then man(5) too will be formatted using mandoc(1). I.e., the MandocAnalyzerFactory MATCHER will also match ".TH" if a mandoc(1) binary is specified.

A single file, mandoc.css, is imported from http://mdocml.bsd.lv with its one-clause license included under LICENSE-mandoc.txt.

Thank you.

### CODE REVIEW

**Comment by tarzanek** [comment]
I will merge after you resolve the conflict @idodeclare

**Comment by tarzanek** [comment]
I am actually very surprised about all your changes, very nicely done

**Comment by idodeclare** [comment]
> very nicely done

@tarzanek , thank you!

**Comment by idodeclare** [comment]
OK that resolved it.

**Comment by tarzanek** [comment]
merging, let's get it rolling ...

**Pull request merged**
