### PR TITLE
Update list of supported VC systems, from http://opengrok.github.io

### PR DESCRIPTION
**Pull request by kenahoo**

### CODE REVIEW

**Comment by tarzanek** [comment]
thank you sir!
accepting

**Comment by tarzanek** [comment]
one last thing, I hope you're OK with OCA for this patch, http://www.oracle.com/technetwork/community/oca-486395.html
If not let me know and I will backout

**Comment by kenahoo** [comment]
I'm okay with the terms of the OCA, do I need to do anything?

**Comment by tarzanek** [comment]
Thnx
All is done and your change is integrated.
Thank you
L

**Pull request merged**
