### PR TITLE
ui changes

### PR DESCRIPTION
**Pull request by tulinkry**
This should address #1226

> A) The new homepage design uses too large fonts for the sections.
> B) Also some default expansions of short sections would IMO make sense.
> For sections with 1-3/4 children it is a waste of time to have to go and expand.
> C) The show all button is in contrary very small and "hurts eyes"
> D) For expansion everywhere else we use + sign shouldn't we use the same on homepage?
> E) The home page is incorrectly aligned as well the top starts right on the left margin, the sections seem to be centered.
> F) Overall the font sizes aren't really harmonized and could use some help, good example is the search field for picking project.

A) I put them down a little bit
B) Added for < 5. However as it's visible in the demo, for many groups it isn't that much practical.
C) Show button is the same size like all other buttons on the main page
D) Replaced
E) I don't see/understand that
F) I made the text input font bigger while the select options smaller

 and #1228.

Replaced by the color of a button. I'm not sure what other I could use - grey (is already the background), white (all over the page), orange (too much aggresive)

[Demo](http://virtual99.cz.oracle.com/ui/) with many groups and projects.

### CODE REVIEW

**Comment by tarzanek** [comment]
@tulinkry  can you please resolve the conflict?

**Comment by tulinkry** [comment]
Resolved.
Again I'd like to remind that I didn't get this point:
> E) The home page is incorrectly aligned as well the top starts right on the left margin, the sections seem to be centered.

**Comment by tarzanek** [comment]
@nerakhon Honzo? E) ?

**Comment by nerakhon** [comment]
Put the page on at least 24 inch LCD and check alignment of sections. I will provide a screenshot on Monday if necessary.

**Comment by tulinkry** [comment]
If it was this, then the commit has been updated
screenshot from 2016-10-31 11-58-10
to this:
screenshot from 2016-10-31 11-58-37

**Comment by nerakhon** [comment]
screen shot 2016-10-31 at 12 56 05

**Comment by tulinkry** [comment]
Aligned to the right - opened:
screenshot from 2016-10-31 16-18-51
Collapsed:
screenshot from 2016-10-31 16-19-14
Without groups:
screenshot from 2016-10-31 16-19-54

**Comment by nerakhon** [comment]
one last nit, did you consider making the right text box the same height as the left ones ot vice versa?

**Comment by tarzanek** [comment]
well actually lgtm, can I merge @nerakhon ? :)

**Comment by nerakhon** [comment]
I would ask for the fix of the textbox sizes afterwards I am keen to give +1.

**Comment by tulinkry** [comment]
Now at the same size
screenshot from 2016-11-03 15-10-31

**Comment by tarzanek** [comment]
:) thnx guys, merging

**Pull request merged**
