### PR TITLE
Ignore LIB and PDB files.

### PR DESCRIPTION
**Pull request by moisei**
LIB and PDB files are binary files.
following discussion is at https://github.com/OpenGrok/OpenGrok/issues/1070#issuecomment-196912718

### CODE REVIEW

**Comment by tarzanek** [comment]
This looks ok
I just need you to agree with oca http://www.oracle.com/technetwork/community/oca-486395.html#r

Or you did it already?

**Comment by moisei** [comment]
I sent it to oracle  just now.

On Tue, Mar 15, 2016 at 9:16 PM, Lubos Kosco <notifications@github.com>
wrote:

> This looks ok
> I just need you to agree with oca
> http://www.oracle.com/technetwork/community/oca-486395.html#r
>
> Or you did it already?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenGrok/OpenGrok/pull/1075#issuecomment-196981126>
>



-- 
Best Regards,
Moisei

**Comment by tarzanek** [comment]
I just got your OCA
accepting, thank you!

Will you have a look at exposing the IgnoreAnalyzerFactory using -A ?

**Comment by moisei** [comment]
Unfortunately, I am fully booked until Jun, not sure I could have a look at it before that.
Is there a way to validate my fix somehow? I've tried to install it on test platform but still I see a content of a lib file when click on it.

**Comment by tarzanek** [comment]
ideal validation is to write a junit test, this way OpenGrok gets a guard so this won't be broken again ...
we run junit tests as part of every pull req, so no one will ever break your change, if you "wrap it" with a test

**Pull request merged**
