### PR TITLE
Support for Resin

### PR DESCRIPTION
**Pull request by lewellyn**
Adds support for Resin to the OpenGrok script and web.xml as noted in #1178.

### CODE REVIEW

**Comment by tarzanek** [comment]
hi
thnx for the change
just two things - oca:
http://www.oracle.com/technetwork/community/oca-486395.html
either say here you are ok and accept it
OR go print, sign, scan and mail back to Oracle
for me to be able to accept your push

and then -
can you test your changed xml with tomcat?
it should work, I know,. but just to be 100% sure ...

tia
L

**Comment by lewellyn** [comment]
I accept the OCA. (I guess my SCA doesn't apply anymore. ;) )

I plan on fully testing in Glassfish and Tomcat this evening or weekend. It appeared to work with a cursory test, but I also want to be careful.

**Comment by tarzanek** [comment]
yeah, SCAs were not migrated unfortunately :(
will merge once I have a go from you on tomcat tests
tia
L

**Comment by tarzanek** [comment]
hi @lewellyn how did your tests end up?
can I merge this? :)

**Comment by tarzanek** [comment]
merging, thanks @lewellyn

**Pull request merged**
