### PR TITLE
Allow "@" in checkout paths

### PR DESCRIPTION
**Pull request by caminada**
- allow to checkout repositories with paths containing "@" (e.g.  sources/OpenGrok@master, sources/OpenGrok@0.12-stable)

### CODE REVIEW

**Comment by caminada** [comment]
Diffs don't work if the checkout path contains "@". With the above patch it's possible to have repository aths (and project names in the web GUI) like sources/OpenGrok@master or sources/OpenGrok@0.12-stable

**Comment by tarzanek** [comment]
thank you, looks good
I need you to agree with OCA here for this patch(since this diff is small), or print/sign/scan/mail it to Oracle (and future patches will be accepted automagically) - http://www.oracle.com/technetwork/community/oca-486395.html

**Comment by caminada** [comment]
Ok, I've sent the signed OVA but didn't hear anything from them yet.

**Comment by tarzanek** [comment]
yeah, it takes a day or two, I will know it asap, since the person responsible always pings me or vladak first thing, let's hope this person doesn't do vacation :)

**Comment by tarzanek** [comment]
hi @caminada 
they pinged me that the pdf that came in was broken (unreadable, last part of it missing, hence they couldn't open it :( )
can you please resend?

**Comment by tarzanek** [comment]
i just recieved the oca
thank you, merging

**Pull request merged**
