### PR TITLE
Feature/perlwork

### PR DESCRIPTION
**Pull request by idodeclare**
(Sorry, I had accidentally left a one-char change I was testing to PerlXref.lex:146 that should have been reverted. Also, sorry that I had not run the test fixture before raising the first version of this request.)

Hello,

Please consider this patch to PerlXref.lex with the principal change:

* Handle Perl quote-like operators generally plus Here-documents    

I made some minor additional PerlXref revisions too:
* do not link from inside non-interpolating quote-like operators
* allow multi-line strings -- i.e., do not terminate "s"-state prematurely
* add a '#' to {URIChar}
* update main.pl test file to include quote-like- and Here- examples

(I e-mailed my OCA to oracle-ca_us today.)

### CODE REVIEW

**Comment by tarzanek** [comment]
very nice, thank you

**Comment by tarzanek** [comment]
it'd be cool to add automated tests that verify the xref output to setup guards of your work
(but that can obviously be part of next pull request)
I guess once the OCA is on file I'd merge it ...
@vladak can we merge?

**Comment by vladak** [comment]
Yep, merge.

**Comment by tarzanek** [comment]
merged, thank you @idodeclare , keep them coming!

**Pull request merged**
