### PR TITLE
Accurev Repository Update Enhancement

### PR DESCRIPTION
**Pull request by ozankiraz**
PR related to : #1441

### CODE REVIEW

**Comment by ozankiraz** [comment]
As far as I know CI doesn't have accurev installed, so I didn't write any unit tests

**Comment by vladak** [comment]
note that if you say in commit message (on separate line) `fixes #1441`, the issue will be automatically closed on merge. This is preferred way.

**Comment by ozankiraz** [comment]
@vladak Thanks for the tip, I didn't know that. Do I need to make any changes for this one?

**Comment by vladak** [comment]
squash the 2 csets into 1 and add the `fixes #1441` message.

**Comment by ozankiraz** [comment]
@vladak I followed these steps and added fixes #1441 : https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

PR still looks same, not sure if this is default behavior.

**Comment by vladak** [comment]
Still see 6 commits: https://github.com/OpenGrok/OpenGrok/pull/1444/commits

You need to forcibly push to rewrite history in your github repo.

**Comment by ozankiraz** [comment]
@vladak Commits squashed into one

**Comment by vladak** [comment]
Merged. For the next time the `fixes #<issue>` needs to be in the commit message.

**Pull request merged**
