### PR TITLE
Add classes to support Ada analysis

### PR DESCRIPTION
**Pull request by idodeclare**
Hello,

Please consider for integration this patch to support analysis for the Ada programming language (issue #403).

Thank you.

### CODE REVIEW

**Comment by tarzanek** [comment]
respect!

**Comment by tarzanek** [comment]
merging, if you're OK with it

**Comment by tarzanek** [comment]
(and thank you, this is a wonderful commit)

**Comment by idodeclare** [comment]
My pleasure :)

**Pull request merged**
