### PR TITLE
new intelligence window

### PR DESCRIPTION
**Pull request by tulinkry**
The intelligence window is under new jquery coat. That should make the further maintenance and usability easier.

It comes with some new features, mainly
 - the window is by default draggable 
    - this can be turned off with:
    ```
    $.intelligenceWindow.init({draggable: false});
    ```

 - previous/next links for jumping among the symbols in a file

The doc is updated for the intelligence window and also for older feature - diff jumper.

Internal demo [here](http://virtual99.cz.oracle.com/intelligence-window/)

### CODE REVIEW

**Comment by tarzanek** [comment]
I like this
also I think it could be used for onMouse over changeset logs when doing annotate ... (to get a better popup window than default hover)

**Comment by tarzanek** [comment]
+ please fix the junit, it expects a bit different xref

**Comment by tulinkry** [comment]
> please fix the junit, it expects a bit different xref

It should be ready now

> also I think it could be used for onMouse over changeset logs when doing annotate ... (to get a better popup window than default hover)

With the update of jquery to 3.1.0 (#1145) I added a new version of tooltip from jquery-ui which seems fine to me right now. Maybe it could be enough to just play with the options of that tooltip

**Comment by tarzanek** [comment]
thnx, merging

**Pull request merged**
