### PR TITLE
adding a select picker to the file type

### LINKED ISSUE #1510: Type selector should use jquery
The Type selector should switch to jquery to match project picker and allow to search by typing.

### PR DESCRIPTION
**Pull request by tulinkry**
fixes #1510

screenshot from 2017-04-18 15-08-52

### CODE REVIEW

**Comment by vladak** [comment]
I wonder how this could work with multiple selected file projects.

**Comment by tulinkry** [comment]
I'm curious as well. I guess that the backend is not implemented

**Comment by vladak** [comment]
Can you file a new enhancement to track this ?

**Comment by vladak** [comment]
how does it look like when no file type is selected ?

**Comment by vladak** [comment]
Maybe consider an alternative: instead of displaying the selected type next to the selector, the selected type(s) can be displayed in the selector.

**Comment by tulinkry** [comment]
> how does it look like when no file type is selected ?

screenshot from 2017-04-18 16-42-18

> Can you file a new enhancement to track this ?

1537

**Comment by tulinkry** [comment]
> Maybe consider an alternative: instead of displaying the selected type next to the selector, the selected type(s) can be displayed in the selector.

I tried to play with this but it's not fairly simple with the select-picker we use. That could be the next step after this.

**Comment by vladak** [comment]
Alright. Will this exhibit same behavior as described in #1519 ?

**Comment by tulinkry** [comment]
Yes this is just a replacement for the old select which is hidden afterwards. However there are less values in the project picker so there should not be that ugly jump.

But with #1519 this should be possibly taken into account as well.

**Comment by vladak** [comment]
Okay, merging.

**Pull request merged**
