### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
> OCA basically means that you won't be sueing [sic]
> [An] Alternative is to ...
> ... is only valid for [the] single pull request.

I agree not to sue.

### CODE REVIEW

**Comment by tarzanek** [comment]
:-D
Thank you sir, looks good!

**Comment by tulinkry** [comment]
10 invalid copyrights:

```log
Testcase: testCopyrights[1](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/src/org/opensolaris/opengrok/analysis/sh/ShXref.lex has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
junit.framework.AssertionFailedError: File OpenGrok/src/org/opensolaris/opengrok/analysis/sh/ShXref.lex has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Testcase: testCopyrights[21](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/src/org/opensolaris/opengrok/analysis/document/TroffXref.lex has been changed but contains an old copyright. (expected:<2017> but was:<2010>)
junit.framework.AssertionFailedError: File OpenGrok/src/org/opensolaris/opengrok/analysis/document/TroffXref.lex has been changed but contains an old copyright. (expected:<2017> but was:<2010>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Testcase: testCopyrights[22](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/src/org/opensolaris/opengrok/analysis/javascript/JavaScriptXref.lex has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
junit.framework.AssertionFailedError: File OpenGrok/src/org/opensolaris/opengrok/analysis/javascript/JavaScriptXref.lex has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Testcase: testCopyrights[32](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/platform/solaris/ips/create.sh has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
junit.framework.AssertionFailedError: File OpenGrok/platform/solaris/ips/create.sh has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Testcase: testCopyrights[36](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/web/js/diff-0.0.1.js has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
junit.framework.AssertionFailedError: File OpenGrok/web/js/diff-0.0.1.js has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Testcase: testCopyrights[40](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/src/org/opensolaris/opengrok/analysis/javascript/Consts.java has been changed but contains an old copyright. (expected:<2017> but was:<2011>)
junit.framework.AssertionFailedError: File OpenGrok/src/org/opensolaris/opengrok/analysis/javascript/Consts.java has been changed but contains an old copyright. (expected:<2017> but was:<2011>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Testcase: testCopyrights[42](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/src/org/opensolaris/opengrok/web/EftarFileReader.java has been changed but contains an old copyright. (expected:<2017> but was:<2014>)
junit.framework.AssertionFailedError: File OpenGrok/src/org/opensolaris/opengrok/web/EftarFileReader.java has been changed but contains an old copyright. (expected:<2017> but was:<2014>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Testcase: testCopyrights[47](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/web/js/tablesorter-parsers-0.0.1.js has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
junit.framework.AssertionFailedError: File OpenGrok/web/js/tablesorter-parsers-0.0.1.js has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Testcase: testCopyrights[65](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/src/org/opensolaris/opengrok/analysis/executables/ELFAnalyzer.java has been changed but contains an old copyright. (expected:<2017> but was:<2013>)
junit.framework.AssertionFailedError: File OpenGrok/src/org/opensolaris/opengrok/analysis/executables/ELFAnalyzer.java has been changed but contains an old copyright. (expected:<2017> but was:<2013>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Testcase: testCopyrights[67](org.opensolaris.opengrok.util.CopyrightTest):	FAILED
File OpenGrok/web/js/repos-0.0.1.js has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
junit.framework.AssertionFailedError: File OpenGrok/web/js/repos-0.0.1.js has been changed but contains an old copyright. (expected:<2017> but was:<2016>)
	at org.opensolaris.opengrok.util.CopyrightTest.testCopyrights(CopyrightTest.java:163)


Test org.opensolaris.opengrok.util.CopyrightTest FAILED
```

**Comment by tarzanek** [comment]
@tulinkry thnx
will fix them in subsequent push

**Comment by jsoref** [comment]
Fwiw, as a general rule, I personally would never change copyrights for simple spelling fixes.

They should fail a test which is related to:
"4. Works Without Authorship/Facts" in https://www.plagiarismtoday.com/2010/01/08/5-things-that-cant-be-copyrighted/
Essentially there is a level of triviality for which I've can't claim copyright.

Obviously, every project can have its own opinion and should have its own lawyers. And having a general rule (and tool) for updating copyright dates is a good thing.

This edge is fairly complicated and generally too complicated for any tool.

I obviously can't stop someone from changing another single character (or potentially four characters if the previous change was before 2000), but I feel it's worth it to explain why my patches wouldn't.

**Comment by tarzanek** [comment]
@jsoref (thanks for OCA paperwork)
:-D
we just change the year whenever we touch the file ...
but I guess we will just move to an approach to change the copyright years just before release, based on @tulinkry 's tool

**Comment by tulinkry** [comment]
the tool can be be integrated with travis to fail the tests at least

**Pull request merged**
