### PR TITLE
Replace Java 9 deprecated calls with appropriate substitutes

### PR DESCRIPTION
**Pull request by Orviss**
When compiling with Java 9 deprecation warnings were shown so I repaired them.

Thanks for review :)

### CODE REVIEW

**Comment by tarzanek** [comment]
I suppose these changes won't compile with 1.8 anymore, will they ?

**Comment by Orviss** [comment]
Why wouldn't they? You can also see that the build passes and I believe that travis has still Java 8.

**Comment by vladak** [comment]
Could you maybe summarize the types of problems being fixed in this PR ? Otherwise I have no other comments.

**Comment by Orviss** [comment]
Mainly I changed:
<https://docs.oracle.com/javase/9/docs/api/java/lang/Class.html#newInstance--> to `getDeclaredConstructor().newInstance()` which propagated some new exceptions
and
<https://docs.oracle.com/javase/9/docs/api/java/lang/Long.html#Long-long-> for which I used autoboxing/unboxing

**Comment by vladak** [comment]
thanks, merging.

**Pull request merged**
