### PR TITLE
jquery 3.1.0

### PR DESCRIPTION
**Pull request by tulinkry**
I upgraded the version of jquery in OpenGrok. I used that jquery migrate script for going up to 3.1.0.

**Migration caused that the depending javascripts also needed to be updated**
- tablesorter -> old => used its up-to-date fork
- tooltip (annotations) -> old => replaced by tooltip in jquery-ui

**Moreover I organized the js code in a special js subdirectory so it is more clean.**

There are couple of js and css files now, maybe we should consider to minify them for the production.

**There are only two deprecated problems, however they are not in our code.**
From my point of view this is ok, we can just wait when the two modules will release their next fixed version. Tablesorter seems very active, I believe that jquery-ui is as well.
- One is in the new version of tablesorter
```
"JQMIGRATE: jQuery.fn.unbind() is deprecated" jquery-migrate-3.0.0.js:62:4
console.trace(): jquery-migrate-3.0.0.js:64
migrateWarn() jquery-migrate-3.0.0.js:64
.unbind() jquery-migrate-3.0.0.js:423
a.tablesorter.bindEvents() jquery.tablesorter-2.26.6.min.js:2
a.tablesorter.setup() jquery.tablesorter-2.26.6.min.js:2
a.fn.tablesorter/<() jquery.tablesorter-2.26.6.min.js:3
.each() jquery-3.1.0.min.js:2
r.prototype.each() jquery-3.1.0.min.js:2
a.fn.tablesorter() jquery.tablesorter-2.26.6.min.js:3
<anonymous> utils.js:463
g/</j() jquery-3.1.0.min.js:2
g/</k<() jquery-3.1.0.min.js:2

"JQMIGRATE: jQuery.fn.bind() is deprecated" jquery-migrate-3.0.0.js:62:4
console.trace(): jquery-migrate-3.0.0.js:64
migrateWarn() jquery-migrate-3.0.0.js:64
.bind() jquery-migrate-3.0.0.js:419
a.tablesorter.bindEvents() jquery.tablesorter-2.26.6.min.js:2
a.tablesorter.setup() jquery.tablesorter-2.26.6.min.js:2
a.fn.tablesorter/<() jquery.tablesorter-2.26.6.min.js:3
.each() jquery-3.1.0.min.js:2
r.prototype.each()
```
- Second is in the new version of jquery-ui
```
"JQMIGRATE: jQuery.unique is deprecated, use jQuery.uniqueSort" jquery-migrate-3.0.0.js:62:4
console.trace(): jquery-migrate-3.0.0.js:64
migrateWarn() jquery-migrate-3.0.0.js:64
migrateWarnProp/<.get() jquery-migrate-3.0.0.js:75
i() jquery-ui-1.12.0-custom.min.js:6
t.Widget.prototype._classes() jquery-ui-1.12.0-custom.min.js:6
t.Widget.prototype._toggleClass() jquery-ui-1.12.0-custom.min.js:6
t.Widget.prototype._addClass() jquery-ui-1.12.0-custom.min.js:6
._create()
```

### CODE REVIEW

**Comment by tarzanek** [comment]
lgtm
the only problem I have is caching of js sources in browsers
this is usually workarounded by versioning them in filename, or add "?version=xx" into their url
anyways, since we moved them to new dir, this won't be a problem for this release, but next release will suffer, however, let's solve it, once this prob arises ;)
merging, thank you sir!

**Comment by tulinkry** [comment]
I would bet that most of the people who use grok also know `ctrl+shift+delete` or `ctrl+r` or `ctrl+shift+r` shortcuts for cleaning the cache or force reload.

**Comment by tulinkry** [comment]
This also fixes #1142. When the date is not parseable then current timestamp is taken.

**Comment by tulinkry** [comment]
And also this fixes #1106. The updated jquery-ui can handle the long lines.
Except when there is a really long single word which is not typical use case.

**Pull request merged**
