### PR TITLE
changing the scopes color to darkgray

### LINKED ISSUE #1008: Scopes UI enhancements
In pull req #904 2 simple changes were proposed to Scopes UI:

- [x] add at least word 'in ' before scope name in search context - for regular user it may not be clear what the 'name()' really means.
- [ ] blue is nice, but too much visible compared to search results, 'darkgray' works good for me. Scopes are helpful, but search results are still more important.

### PR DESCRIPTION
**Pull request by tulinkry**
fixes #1008

### CODE REVIEW

**Comment by vladak** [comment]
got a screenshot ?

**Comment by tulinkry** [comment]
Sure I have

screenshot from 2017-01-27 12-18-32

**Comment by vladak** [comment]
I have to say the colored scopes were better then the dark gray. Maybe the blue could be toned a bit down ?

**Comment by tulinkry** [comment]
The first is the current color (dodgerblue).

steelblue:
screenshot from 2017-02-06 14-01-56
royalblue:
screenshot from 2017-02-06 14-02-08
teal:
screenshot from 2017-02-06 14-03-18
midnightblue:
screenshot from 2017-02-06 14-03-55
darkslategray:
screenshot from 2017-02-06 14-04-47
indigo:
screenshot from 2017-02-06 14-05-33
navy:
screenshot from 2017-02-06 14-06-12

**Comment by vladak** [comment]
Personally I like steelblue most.

**Comment by jfriedel** [comment]
steelblue +1

**Comment by tulinkry** [comment]
Changed to steelblue

**Pull request merged**
