### PR TITLE
allowing markdown readmes to be rendered as html

### PR DESCRIPTION
**Pull request by tulinkry**
As suggested in #995 this is the implementation which uses javascript converter. I'm not sure if it is really useful, but it's not bad.

Examples (internal):
[example 1](http://virtual99.cz.oracle.com/markdown/xref/application/)
[example 2](http://virtual99.cz.oracle.com/markdown/xref/caching)
[example 3](http://virtual99.cz.oracle.com/markdown/xref/latte)

### CODE REVIEW

**Comment by vladak** [comment]
I'd put the readme contents into a frame or at least use some light background - like github does.

**Comment by tulinkry** [comment]
Check the examples again :)

**Comment by vladak** [comment]
Looks better except the long lines crawl out of the grey frame which looks terrible.

**Comment by vladak** [comment]
Also, just for completeness: I am a bit worried that this is XSS prone.

**Comment by tulinkry** [comment]
And I would like to point out [this fact](https://github.com/showdownjs/showdown#xss-vulnerability) that processing markdown is not XSS safe!

**Comment by tulinkry** [comment]
Ok so as mentioned in the [code](https://github.com/OpenGrok/OpenGrok/pull/1253/files#diff-d117286e3441fbba4b026d0dc13a2cd6R1114), the converter behaviour can be completely disabled by commenting out the init call and it falls back to the old behaviour (just prints the readme source code).

**Comment by tarzanek** [comment]
so is there a way to fix/sanitize  the possible xss ?

**Comment by tulinkry** [comment]
As described [here](https://github.com/showdownjs/showdown/wiki/Markdown's-XSS-Vulnerability-(and-how-to-mitigate-it)) I added a xss filter after the markdown process.

However the problem was more difficult - not to render the html in the page, so I decided to take it through ajax - the markdown readmes are loaded through ajax call and then processed, filtered and rendered. Maybe this is too complicated and we should just render the readmes as they are.

I used [this xss filter](https://github.com/leizongmin/js-xss) which seems ok (but I haven't looked into much details).

**Comment by tarzanek** [comment]
version missing for xss.min.js

**Comment by tarzanek** [comment]
(make the version part of the file name, this will help with caching later on)

**Comment by tulinkry** [comment]
> Looks better except the long lines crawl out of the grey frame which looks terrible.
Can't reproduce this

**Comment by tarzanek** [comment]
@vladak I am OK with merge, if you're OK, then please merge! :)

**Comment by vladak** [comment]
Still need to see if the issue with long lines reported earlier persists.

**Comment by vladak** [comment]
It seems to be resolved, merging.

**Pull request merged**
