### PR TITLE
adding sample plugins to maven build

### PR DESCRIPTION
**Pull request by tulinkry**
mentioned in #1131

I'm not sure if this is the correct way but I tested it with netbeans and jenkins builds

### CODE REVIEW

**Comment by tarzanek** [comment]
lgtm, travis looks ok, which is the only thing needed
thank you sir!

**Comment by tarzanek** [comment]
AH, you just added it to ant build
maven build happens in pom.xml
anyways I am going to accept it 

fwiw - check OpenGrokMaven job in internal jenkins on how to use maven with OpenGrok

**Comment by tarzanek** [comment]
so the commit name is a bit misleading, but I guess we will just let it go
please look at pom.xml and adjust so this test happens in mvn (travis is based on mvn) too

**Comment by tulinkry** [comment]
I don't see it in the travis build, I will add it

**Pull request merged**
