### PR TITLE
directory name of RepositoryInfo should be stored as relative path

### PR DESCRIPTION
**Pull request by vladak**
This is a bit of a hack to store only relative paths in `RepositoryInfo` object encoding.

### CODE REVIEW

**Comment by tarzanek** [comment]
merging
I suppose all this transient stuff is just to have proper config.xml ?

**Comment by tarzanek** [comment]
ah, ok, cannot merge
can you please solve conflicts and merge @vladak ?

thnx
L

**Comment by vladak** [comment]
Even though I merged with upstream/master according to https://help.github.com/articles/syncing-a-fork/, Github seems to think that this has conflict even though they are not listed.

**Comment by vladak** [comment]
Anyhow, I found that there is some deduplication to do in the `SubversionRepository` code.

**Pull request merged**
